# Generated by Django 5.2.4 on 2026-05-14 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EhliyetSinifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('aciklama', models.TextField()),
                ('yas_siniri', models.IntegerField(default=18)),
                ('fiyat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='IletisimBasvurusu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=15)),
                ('mesaj', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('arandi_mu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SaatAraligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(help_text='Örn: 13:00 - 14:00', max_length=20)),
                ('sira', models.IntegerField(default=0, help_text='Listeleme sırası')),
            ],
            options={
                'verbose_name': 'Saat Aralığı',
                'verbose_name_plural': 'Saat Aralıkları',
                'ordering': ['sira'],
            },
        ),
        migrations.CreateModel(
            name='SiteAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_numarasi', models.CharField(max_length=20, verbose_name='WhatsApp Numarası (Örn: 905xxxxxxxxx)')),
                ('instagram_adresi', models.CharField(max_length=200, verbose_name='Instagram Profil Linki')),
                ('eposta_adresi', models.EmailField(max_length=254, verbose_name='E-Posta Adresi')),
                ('konum_linki', models.TextField(verbose_name='Google Haritalar Embed Kodu/Linki')),
                ('adres_metni', models.TextField(blank=True, null=True, verbose_name='Açık Adres')),
                ('site_basligi', models.CharField(default='Öz Asarcık Sürücü Kursu', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.TextField()),
                ('secenek_a', models.CharField(max_length=255)),
                ('secenek_b', models.CharField(max_length=255)),
                ('secenek_c', models.CharField(max_length=255)),
                ('secenek_d', models.CharField(max_length=255)),
                ('dogru_cevap', models.CharField(max_length=1)),
                ('kategori', models.CharField(choices=[('trafik', 'Trafik ve Çevre'), ('saglik', 'İlk Yardım ve Sağlık'), ('motor', 'Motor ve Araç Tekniği'), ('adab', 'Trafik Adabı')], db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Egitmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=15)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eğitmen',
                'verbose_name_plural': 'Eğitmenler',
            },
        ),
        migrations.CreateModel(
            name='KayitEvrak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('aciklama', models.CharField(blank=True, max_length=255, null=True)),
                ('zorunlu_mu', models.BooleanField(default=True)),
                ('ilgili_siniflar', models.ManyToManyField(blank=True, related_name='evraklar', to='kurs.ehliyetsinifi')),
            ],
        ),
        migrations.CreateModel(
            name='Kursiyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('tc_no', models.CharField(max_length=11, unique=True)),
                ('telefon', models.CharField(max_length=15)),
                ('kayit_tarihi', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('egitmen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kursiyerleri', to='kurs.egitmen', verbose_name='Eğitmen')),
                ('ehliyet_sinifi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kurs.ehliyetsinifi')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(blank=True, db_index=True, null=True)),
                ('dolu_mu', models.BooleanField(default=False)),
                ('katilim_durumu', models.CharField(choices=[('beklemede', 'Beklemede'), ('geldi', 'Geldi'), ('gelmedi', 'Gelmedi')], default='beklemede', max_length=20)),
                ('egitmen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kurs.egitmen')),
                ('ehliyet_sinifi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kurs.ehliyetsinifi')),
                ('kursiyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kurs.kursiyer')),
                ('saat_dilimi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kurs.saataraligi')),
            ],
        ),
        migrations.CreateModel(
            name='YanlisSoru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secilen_cevap', models.CharField(blank=True, max_length=1, null=True)),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurs.soru')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yanlis_sorular', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'soru')},
            },
        ),
    ]
