# Generated by Django 5.2.4 on 2026-06-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehliyetsinifi',
            name='resim_yolu',
            field=models.CharField(blank=True, default='img/ehliyet/varsayilan.jpg', max_length=200, null=True),
        ),
    ]
