# Generated by Django 5.2.4 on 2026-06-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0002_ehliyetsinifi_resim_yolu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehliyetsinifi',
            name='resim_yolu',
            field=models.CharField(blank=True, default='images/ehliyet/varsayilan.jpg', max_length=200, null=True),
        ),
    ]
